### ISSUE TITLE
Autofix option?

### ISSUE THREAD

**Issue by RedTn** [rwjblue/ember-cli-template-lint#288]
Great addon! I'm having a tough time finding if there is a --fix option like in eslint (eslint . --fix) where it will automatically fix files that fail the lint rules. Is there an option for this or is it missing?

**Comment by rwjblue** [comment]
Sadly no, but it is definitely something that we want to make happen at some point.

**Comment by BryanCrotaz** [comment]
Still no autofix? I have 1000+ errors in old templates :(

**Comment by stevetyler** [comment]
Myself and @deepan83 will be raising a PR soon

**Comment by ferpintado** [comment]
Any update on this?

**Comment by piotrpalek** [comment]
I've got a different, but related question. Does everybody just manually indent theri .hbs files? I've just tried to "format document" in VSCode and it just flattens all of my nesting.. do glimmer templates have no support in even the most popular editor?

**Comment by akankshadharkar** [comment]
Hey, 
Have we managed to get an update on this? 
Curious, as I feel my indentation is correct, yet I keep getting this error and it's failing my tests due to not passing the TemplateLint :(
Tried changing the indentations, as well. 

Some details: 
I'm using **VSCode** as my IDE. 
Using ember-cli **3.12.0** and OS is RHEL 7.6

![indentation (1)](https://user-images.githubusercontent.com/12375430/71071477-b303a300-21a2-11ea-9d65-50c6ef719542.png)

**Comment by artemv** [comment]
> I've got a different, but related question. Does everybody just manually indent theri .hbs files? I've just tried to "format document" in VSCode and it just flattens all of my nesting.. do glimmer templates have no support in even the most popular editor?

I just tried to find anything but couldn't - resorted to autoformatting with [prettier](https://prettier.io/docs/en/install.html) tool like this: `prettier --parser glimmer my/path/to/reviewable-item.hbs > 1 && mv 1 my/path/to/reviewable-item.hbs`
