### ISSUE TITLE
block-indentation required handlebars-expressions to be on their own line

### ISSUE THREAD

**Issue by mydea** [rwjblue/ember-cli-template-lint#59]
With block-indentation, the following throws an error:

```hbs
<div>
  {{t 'Use the following ID:'}}
  {{t 'id-prefix-'}}{{id}}
</div>
```

However, in some cases this can be necessary, e.g. if you do not want to have whitespace between two elements or translated strings. I feel that non-block handlebars expressions should not be required to be in their own lines.

**Comment by mixonic** [comment]
@mydea you can always use [whitespace control](http://handlebarsjs.com/expressions.html#whitespace-control), and should!

```hbs
<div>
  {{t 'Use the following ID:'}}
  {{t 'id-prefix-' ~}}
  {{id}}
</div>
```

Additionally, you should be able to disable this rule [per template](https://github.com/rwjblue/ember-cli-template-lint#per-template) and [project wide](https://github.com/rwjblue/ember-cli-template-lint#project-wide).

I'm going to close that since I think this should be sufficient, but we can always re-open if there are further thoughts. /cc @rwjblue

**Comment by mydea** [comment]
Oh, I did not know about that. Great to know! Thanks for pointing this out to me. 

As a side note, it might be nice to add this to the Ember guides.
